spring.application.name=unipdi

server.port=8080

# AWS S3 & DynamoDB Configuration
spring.cloud.aws.region.static=${AWS_REGION:us-east-1}
spring.cloud.aws.credentials.access-key=${AWS_ACCESS_KEY_ID:test}
spring.cloud.aws.credentials.secret-key=${AWS_SECRET_ACCESS_KEY:test}
aws.s3.bucket-name=${AWS_S3_BUCKET_NAME:unipdi-bucket}

# Para testes locais com LocalStack (descomente se necessário):
# spring.cloud.aws.s3.endpoint=http://localhost:4566
